name: Docker Build and Push to Aliyun

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发
  pull_request:
    branches:
      - main  # 在 PR 请求推送时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录阿里云 Docker Registry
      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hongkong.aliyuncs.com  # 阿里云 Docker Registry 地址
          username: ${{ secrets.ALIYUN_USERNAME }}  # 使用 GitHub Secrets 中的阿里云用户名
          password: ${{ secrets.ALIYUN_PASSWORD }}  # 使用 GitHub Secrets 中的阿里云密码或令牌

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build --build-arg HUGO_VERSION=0.133.0 -t registry.cn-hongkong.aliyuncs.com/yzhub/kubernetes-website:latest .

      # 推送 Docker 镜像到阿里云
      - name: Push Docker image
        run: |
          docker push registry.cn-hongkong.aliyuncs.com/yzhub/kubernetes-website:latest
